### ISSUE TITLE
Hash error when running with node > 16

### ISSUE THREAD

**Issue by ymougenel** [CommandersAct/ngx-tag-commander#67]
Hello,
I encountered an error when running the project with node >16 (on debian environment).

**Reproducing:**
```bash 
npm install;
npm run start;
```
Tried with versions ( ✅= success, ❌= fail):
- node 14.7.0 => ✅
- node 15.14.0 => ✅
- node 16.20.2 => ✅
- node 17.9.1 => ❌
- node 18.19.0 => ❌
- node 21.1.0 => ❌

**Full stack:**
```
ngx-tag-commander-app@1.0.0 start
ng serve  --open

Node.js version v17.9.1 detected.
Odd numbered Node.js versions will not enter LTS status and should not be used for production. For more information, please see https://nodejs.org/en/about/releases/.
⠋ Generating browser application bundles (phase: setup)...Compiling @angular/core : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/router : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
⠙ Generating browser application bundles (phase: building)...node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at BulkUpdateDecorator.hashFactory (/home/ym/ngx-tag-commander/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/home/ym/ngx-tag-commander/node_modules/webpack/lib/util/createHash.js:46:50)
    at SourceMapSource.updateHash (/home/ym/ngx-tag-commander/node_modules/webpack/node_modules/webpack-sources/lib/SourceMapSource.js:231:8)
    at NormalModule._initBuildHash (/home/ym/ngx-tag-commander/node_modules/webpack/lib/NormalModule.js:880:17)
    at handleParseResult (/home/ym/ngx-tag-commander/node_modules/webpack/lib/NormalModule.js:946:10)
    at /home/ym/ngx-tag-commander/node_modules/webpack/lib/NormalModule.js:1040:4
    at processResult (/home/ym/ngx-tag-commander/node_modules/webpack/lib/NormalModule.js:755:11)
    at /home/ym/ngx-tag-commander/node_modules/webpack/lib/NormalModule.js:819:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.9.1
```

Process finished with exit code 1
```

**Comment by ymougenel** [comment]
Workaround:
```bash
export NODE_OPTIONS=--openssl-legacy-provider
```

**Comment by thepiwo** [comment]
@ymougenel older angular versions don't work with nodejs > 16, thus the workaround is needed there. We are currently working on an updated verion of the library and example project with latest angular and nodejs support.

**Comment by thepiwo** [comment]
this will be fixed with the release of https://github.com/CommandersAct/ngx-tag-commander/pull/68 supporting newer angular and improving the documentation

**Comment by ymougenel** [comment]
Perfect thank you :+1: 
Could you publish the 3.0.0 version [on npm](https://www.npmjs.com/package/ngx-tag-commander)?

**Comment by thepiwo** [comment]
@ymougenel absolutely, sorry for the delay on this

**Comment by ymougenel** [comment]
Thanks again for your reactivity, 
this issue seems solved

**Comment by thepiwo** [comment]
Very welcome, I'll close this issue then.
